#!/usr/bin/perl

use strict;
use warnings;
use lib '.';
use feature 'say';
use Data::Dump 'pp';

use FurnitureShop;
use FurnitureShop 'hello';
use FurnitureShop::Chair;
use FurnitureShop::Table; # new line

say(hello('fred'));  

say FurnitureShop::Chair->sell('fred');
say FurnitureShop::Table->sell('fred'); # new line
