#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use Data::Dump 'pp';
use Teach::Tutor; # Don't forget to call: submit(<variable>);

my @sorted = sort {
	$b <=> $a
} @ARGV;
say pp(@sorted);
submit(@sorted);