#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

sub modify_string_exclaim {
    my ($r_str) = @_;

    $$r_str = $$r_str . '!';
    1;
}

my $sc = 'Hello';
say $sc; # Output: Hello

modify_string_exclaim(\$sc);
say $sc; # Output: Hello!

