#!/usr/bin/perl

use strict;
use warnings;
use feature ('say', 'state');

my $i = 0;

sub call_me {
    $i++;
    return $i;
}

say "You have called me ".call_me()." times.";
say "You have called me ".call_me()." times.";
say "You have called me ".call_me()." times.";

